<a href="https://colab.research.google.com/github/Pat587/BioinformatykaRoslin2021/blob/main/Bioinformatyka_Ro%C5%9Blin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Wczytanie zbioru danych z użyciem biblioteki pandas
OUTPUT: data_pd

In [ ]:
import pandas as pd
path_to_data = "https://raw.githubusercontent.com/BioBarto/BioinformatykaRoslin2021/main/data_all.txt"
data_pd = pd.read_csv(path_to_data)

data_pd.head()

   grain_yield  pht_height  Heading_Date  ...  SNP_2316  SNP_2317  SNP_2318
0         4869          78          57.5  ...         1        -1        -1
1         4621          74          56.0  ...         1        -1         1
2         4557          66          58.0  ...         1        -1         1
3         5484          77          59.0  ...         1        -1        -1
4         4641          69          55.5  ...         1        -1        -1

[5 rows x 2321 columns]

## Wczytanie zbioru danych z użyciem biblioteki import.url
OUTPUT: data_url

In [ ]:
import urllib.request  # the lib that handles the url stuff
url = "https://raw.githubusercontent.com/BioBarto/BioinformatykaRoslin2021/main/data_all.txt"
file = urllib.request.urlopen(url)

data_url = []
for line in urllib.request.urlopen(url):
    data_url.append(line.decode('utf-8'))

len(data_url)

97

## KOD do analizy zbioru

In [ ]:
#Różnice pomiędzy data_url / data_pd

print(type(data_url))
print(type(data_pd))

<class 'list'>
<class 'pandas.core.frame.DataFrame'>

In [ ]:
#Określam zmieną data - jako listę (nie jako macierz z biblioteki Panda)
data = data_pd

## Testowanie

In [ ]:
print ("Hello word")

Hello word

Po lewej jak kliknięcie w obrazek folderu, jest plik snp_new_out już z wyliczonym dystansem genetycznym. Ponieżej wrzucę opisany kod co robiłam.

Oraz pod nazwą snp.txt to dane z których najpierw usunełąm NA a później obliczyłam dystans.

In [ ]:
snp = read.table(header = F, sep = "", "D:/aktualny pulpit/Magisterka/SEMESTR3/bio_roślin/snp.txt") #nasze dane

In [ ]:
#sprawdzenie ile jest wartosci NA
sum(is.na(snp))

In [ ]:
#usuwanie NA
snp2 = snp[ , colSums(is.na(snp)) == 0]
sum(is.na(snp2))

In [ ]:
#potrzebne biblioteki

library(poppr)

#właściwa funkcja 
  
micdist    <- provesti.dist(snp2) #liczy prawidłowo
mydf<-as.data.frame(as.matrix(micdist))


#zapisywanie jako csv
write.csv(mydf,file = "D:/aktualny pulpit/snp_new_out.csv")

#wczytanie gotowej macierzy z nazwanymi wierszami i kolumnami
distance = read.csv(header = T, sep = ";", "D:/aktualny pulpit/Magisterka/SEMESTR3/bio_roślin/snp_new_out2.csv")

Teraz musimy dobrać "pary" do krzyżówek, według tego co mi Mateusz pisał to jest to w pakiecie: adegenet i find.clusters.

In [ ]:
# kod na pobranie adegenet z githuba, ja nie mogłam inaczej go pobrać

options(
  repos = c(
    zkamvar = "https://zkamvar.r-universe.dev",
    CRAN = "https://cloud.r-project.org"
  )
)
install.packages("adegenet")

library(adegenet) #potrzebny pakiet

#wczytanie gotowej macierzy z nazwanymi wierszami i kolumnami
distance = read.csv(header = T, sep = ";", "D:/aktualny pulpit/Magisterka/SEMESTR3/bio_roślin/snp_new_out2.csv") 

#distance2 = data.frame(distance[1:96])
df.distance = as.data.frame(distance)

#SZUKANIE KLASTRÓW?LICZENIE KLASTRÓW
cluster <- find.clusters(df.distance, max.n=30, n.pca=100, scale=FALSE) #z tego co wiem to max.n moża dawać inne wartości

names(cluster)
cluster$Kstat 
cluster$stat
table(cluster$grp)

In [ ]:
# TESTY - GRUPOWANIE

grouping2 = data.frame(df.distance$X, cluster$grp)
grouping3 = data.frame(df.distance$X4869, cluster$grp)
colnames(grouping2)[1] = 'name'
colnames(grouping2)[2] = 'name2'

In [ ]:
#-----------------------------------------------------------------------------------
#PRZYKŁAD Z NETA
data(eHGDP)

new_eHGDP = df2genind(eHGDP, ploidy=2)
grp <- find.clusters(eHGDP, max.n=50, n.pca=200, scale=FALSE) # zajmuje około 2 minut 
names(grp) 
grp$Kstat 
grp$stat 
table(grp$grp)


grouping = data.frame(eHGDP$tab[1:1350], grp$grp)
colnames(grouping)[1] = 'name'
colnames(grouping)[2] = 'name2'
#-----------------------------------------------------------------------------------